version: 1.6.0.2-{build}
configuration: Release
platform:
- Win32
- x64
shallow_clone: true
environment:
  DXSDK: '%DXSDK_DIR%'
  BOOST_1_60_0: 'C:\Libraries\boost_1_60_0'
before_build:
- cmd: >-
    echo %PLATFORM%

    echo %CONFIGURATION%

    echo cop_%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.7z
build:
  project: ./engine.sln
  verbosity: minimal
after_build:
- cmd: >-
    set COR_PLAT=%PLATFORM%

    IF "%COR_PLAT%" == "Win32" set COR_PLAT=x86

    set BUGTRAP=BugTrap-%COR_PLAT%.dll

    IF "%COR_PLAT%" == "x86" set BUGTRAP=BugTrap.dll

    md dist

    echo ===================== engine files =====================

    md dist\engine

    copy opt\start_%COR_PLAT%.bat dist\engine

    md dist\engine\bin_%COR_PLAT%

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.exe dist\engine\bin_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.dll dist\engine\bin_%COR_PLAT%\

    copy SDK\binaries\%COR_PLAT%\lua51.dll dist\engine\bin_%COR_PLAT%\

    md dist\engine\bin_%COR_PLAT%\lua\jit

    copy SDK\binaries\%COR_PLAT%\lua\jit\* dist\engine\bin_%COR_PLAT%\lua\jit\

    copy SDK\binaries\%COR_PLAT%\%BUGTRAP% dist\engine\bin_%COR_PLAT%\

    md dist\engine\gamedata\scripts

    copy gamedata\scripts\* dist\engine\gamedata\scripts\

    7z a cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z dist\engine\*

    echo appveyor PushArtifact cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z release

    rem echo ===================== engine pdb files =====================

    rem md dist\engine_pdb_%COR_PLAT%

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\*.pdb dist\engine_pdb_%COR_PLAT%\

    rem 7z a cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%_pdb.7z dist\engine_pdb_%COR_PLAT%\*

    echo ===================== sdk files =====================

    md dist\sdk_%COR_PLAT%

    copy SDK\binaries\%COR_PLAT%\MagicFM.dll dist\sdk_%COR_PLAT%\

    copy SDK\binaries\%COR_PLAT%\nvtt.dll dist\sdk_%COR_PLAT%\

    copy SDK\binaries\%COR_PLAT%\%BUGTRAP% dist\sdk_%COR_PLAT%\

    copy SDK\binaries\%COR_PLAT%\lua51.dll dist\sdk_%COR_PLAT%\

    md dist\sdk_%COR_PLAT%\lua\jit

    copy SDK\binaries\%COR_PLAT%\lua\jit\* dist\sdk_%COR_PLAT%\lua\jit\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\xrCore.dll dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\xrCDB.dll dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\xrAPI.dll dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\xrXMLParser.dll dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\luabind.0.9.dll dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\SDK\*.exe dist\sdk_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\SDK\*.dll dist\sdk_%COR_PLAT%\

    7z a cop_compilers_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z dist\sdk_%COR_PLAT%\*

    echo appveyor PushArtifact cop_compilers_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z release

    rem echo ===================== sdk pdb files =====================

    rem md dist\sdk_pdb_%COR_PLAT%

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\xrCore.pdb dist\sdk_pdb_%COR_PLAT%\

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\xrCDB.pdb dist\sdk_pdb_%COR_PLAT%\

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\xrAPI.pdb dist\sdk_pdb_%COR_PLAT%\

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\xrXMLParser.pdb dist\sdk_pdb_%COR_PLAT%\

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\luabind.0.9.pdb dist\sdk_pdb_%COR_PLAT%\

    rem copy intermediate\%PLATFORM%-%CONFIGURATION%\SDK\*.pdb dist\sdk_pdb_%COR_PLAT%\

    rem 7z a cop_compilers_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%_pdb.7z dist\sdk_pdb_%COR_PLAT%\*
artifacts:
- path: .\cop_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release
- path: .\cop_compilers_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release
#- path: .\cop_$(appveyor_repo_tag_name)_$(cor_plat)_pdb.7z
#  name: release
#- path: .\cop_compilers_$(appveyor_repo_tag_name)_$(cor_plat)_pdb.7z
#  name: release
deploy:
- provider: GitHub
  auth_token:
    secure: pXJeBrB1oq+/lPsy2jphy4dRQ542dkJRbAEOD3y/YgSVsoRTSgIt01EI92q9whrl
  artifact: release
  on:
    appveyor_repo_tag: true